// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJwpfz4sPH8t9qY0378KuDaOcESDYbZ0o',
    appId: '1:270216657991:web:d3ad5c603b3451d5424562',
    messagingSenderId: '270216657991',
    projectId: 'smart-subscription',
    authDomain: 'smart-subscription.firebaseapp.com',
    databaseURL: 'https://smart-subscription-default-rtdb.firebaseio.com',
    storageBucket: 'smart-subscription.appspot.com',
    measurementId: 'G-GHK3VTC55W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQt9cFyXwpe_sJrcVGNRitMVMj23JjM9A',
    appId: '1:270216657991:android:d137239867028655424562',
    messagingSenderId: '270216657991',
    projectId: 'smart-subscription',
    databaseURL: 'https://smart-subscription-default-rtdb.firebaseio.com',
    storageBucket: 'smart-subscription.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQbvHYtdKuqlBc7ExhaFQ7CZ2RkSekMxE',
    appId: '1:270216657991:ios:cc77e559eb556984424562',
    messagingSenderId: '270216657991',
    projectId: 'smart-subscription',
    databaseURL: 'https://smart-subscription-default-rtdb.firebaseio.com',
    storageBucket: 'smart-subscription.appspot.com',
    iosClientId: '270216657991-60knuv6kjvs2epv7t6okj2kvo0nb25hi.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQbvHYtdKuqlBc7ExhaFQ7CZ2RkSekMxE',
    appId: '1:270216657991:ios:a5bb1f767a8ff7bf424562',
    messagingSenderId: '270216657991',
    projectId: 'smart-subscription',
    databaseURL: 'https://smart-subscription-default-rtdb.firebaseio.com',
    storageBucket: 'smart-subscription.appspot.com',
    iosClientId: '270216657991-brrnaqt09hu58us3obc3bu7qt4ein007.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirstapp.RunnerTests',
  );
}
