// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3nV_GkDbxuaDpjDEvlF4aXNCc6k7GsBA',
    appId: '1:59276231533:web:0b8f766b105482d64a5064',
    messagingSenderId: '59276231533',
    projectId: 'smartsubscriptions-baa50',
    authDomain: 'smartsubscriptions-baa50.firebaseapp.com',
    storageBucket: 'smartsubscriptions-baa50.appspot.com',
    measurementId: 'G-JN34P84117',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoFeEgNlmN2oS_O7VN9kyZ6txCgJnz5jw',
    appId: '1:59276231533:android:ac5bdbd6550f3da14a5064',
    messagingSenderId: '59276231533',
    projectId: 'smartsubscriptions-baa50',
    storageBucket: 'smartsubscriptions-baa50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlqBCZ435dZzmPmNoX2QLAoAVG9QK_dC0',
    appId: '1:59276231533:ios:a0c9a64cc0ec33844a5064',
    messagingSenderId: '59276231533',
    projectId: 'smartsubscriptions-baa50',
    storageBucket: 'smartsubscriptions-baa50.appspot.com',
    iosBundleId: 'com.example.smartsubscriptions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlqBCZ435dZzmPmNoX2QLAoAVG9QK_dC0',
    appId: '1:59276231533:ios:a0c9a64cc0ec33844a5064',
    messagingSenderId: '59276231533',
    projectId: 'smartsubscriptions-baa50',
    storageBucket: 'smartsubscriptions-baa50.appspot.com',
    iosBundleId: 'com.example.smartsubscriptions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3nV_GkDbxuaDpjDEvlF4aXNCc6k7GsBA',
    appId: '1:59276231533:web:c5c29774ec70eed74a5064',
    messagingSenderId: '59276231533',
    projectId: 'smartsubscriptions-baa50',
    authDomain: 'smartsubscriptions-baa50.firebaseapp.com',
    storageBucket: 'smartsubscriptions-baa50.appspot.com',
    measurementId: 'G-JWHD48K3PX',
  );
}
